name: Listing S3 Buckets  

on:
  push:
    branches:
      - master
    
  workflow_dispatch:

jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS Creentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List S3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: 
          echo "Listing S3 Buckets in region $AWS_REGION"
          aws s3 ls